---
- name: "pull images for {{ docker_compose_file }}"
  command: "docker-compose -f {{ docker_compose_file }} pull"
  changed_when: False

- name: "set .env file for {{ docker_compose_file }}"
  copy:
    content: "{{ docker_compose_env }}"
  when:
    - docker_compose_env is defined

- name: Deploy stack from a compose file
  docker_compose:
    project_src: "{{ docker_compose_file | dirname}}"
    definition:
      - "{{ docker_compose_file | basename}}"
    pull: 'yes'
    remove_orphans: 'yes'